# Generated by Django 5.2.8 on 2026-01-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name_cn', models.CharField(db_index=True, max_length=128, verbose_name='中文名')),
                ('name_en', models.CharField(blank=True, default='', max_length=128, verbose_name='英文名')),
                ('scientific_name', models.CharField(blank=True, default='', max_length=256, verbose_name='学名')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='别名')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='识别特征')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('habitat', models.TextField(blank=True, default='', verbose_name='栖息地')),
                ('diet', models.TextField(blank=True, default='', verbose_name='食性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fish_species',
                'ordering': ['name_cn'],
            },
        ),
    ]
